export const endpoints = {
  health: '/api/health',
  publicSociety: '/api/public/society',
  login: '/api/auth/login',
  me: '/api/auth/me',
  logout: '/api/auth/logout',
  dashboard: '/api/dashboard',
  society: '/api/society',
  bills: '/api/bills',
  billPayments: (id) => `/api/bills/${encodeURIComponent(id)}/payments`,
  billWaivePenalty: (id) => `/api/bills/${encodeURIComponent(id)}/waive-penalty`,
  security: '/api/security',
  guards: '/api/security/guards',
  guard: (id) => `/api/security/guards/${encodeURIComponent(id)}`,
  handover: '/api/security/handover',
  patrol: '/api/security/patrol',
  patrolPoint: (id) => `/api/security/patrol/${encodeURIComponent(id)}`,
  patrolReset: '/api/security/patrol/reset',
  incidents: '/api/security/incidents',
  incident: (id) => `/api/security/incidents/${encodeURIComponent(id)}`,
  staff: '/api/staff',
  staffMember: (id) => `/api/staff/${encodeURIComponent(id)}`,
  staffAttendance: '/api/staff-attendance',
  staffAttendanceFor: (date) => `/api/staff-attendance?date=${encodeURIComponent(date)}`,
  roster: '/api/roster',
  followUps: '/api/follow-ups',
  followUp: (id) => `/api/follow-ups/${encodeURIComponent(id)}`,
  tickets: '/api/tickets',
  ticket: (ticketNo) => `/api/tickets/${encodeURIComponent(ticketNo)}`,
  ticketUpdate: (dbId) => `/api/tickets/${encodeURIComponent(dbId)}`,
};
