export const endpoints = {
  health: '/api/health',
  publicSociety: '/api/public/society',
  login: '/api/auth/login',
  me: '/api/auth/me',
  logout: '/api/auth/logout',
  dashboard: '/api/dashboard',
  society: '/api/society',
  bills: '/api/bills',
  billPayments: (id) => `/api/bills/${encodeURIComponent(id)}/payments`,
  billWaivePenalty: (id) => `/api/bills/${encodeURIComponent(id)}/waive-penalty`,
  tickets: '/api/tickets',
  ticket: (ticketNo) => `/api/tickets/${encodeURIComponent(ticketNo)}`,
  ticketUpdate: (dbId) => `/api/tickets/${encodeURIComponent(dbId)}`,
};
